account/urls.py
from account import views
from django.urls import path, include
from dsgroup import urls as dsgroup_urls
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView



urlpatterns = [

	path('',views.user_login,name='user_login'),
   	#path("signup/",views.register,name="reg"),
	#path("check_user/",views.check_user,name="check_user"),
	path("user_logout/",views.user_logout,name="user_logout"),
	#path("edit_profile/",views.edit_profile,name="edit_profile"),
	#path("change_password/",views.change_password,name="change_password"),
	
]



dashboard/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    
    path('',views.dashboard, name='dashboard'),
    path('register_intern/',views.register_intern, name='register_intern'),
    path('view_interns/',views.view_interns, name='view_interns'),
    path('intern_attendance/',views.intern_attendance, name='intern_attendance'),
    path('intern_attendance_date/',views.intern_attendance_date, name='intern_attendance_date'),
    path('intern_attendance_edit/<str:update_date>',views.intern_attendance_edit, name='intern_attendance_edit'),
    path('intern_attendance_manage/',views.intern_attendance_manage, name='intern_attendance_manage'),
    path('intern_profile/<int:id>',views.intern_profile,name="intern_profile"),
    path('edit_intern/<int:id>',views.edit_intern,name='edit_intern'),
    path('manage_intern/<int:id>',views.manage_intern,name='manage_intern'),
    path('remove_intern/',views.remove_intern,name='remove_intern'),
    # path('search/', views.SearchResultsView.as_view(), name='search_results'),


    path('register_trainees/',views.register_trainees, name='register_trainees'),
    path('view_trainees/',views.view_trainees, name='view_trainees'),
    path('trainee_attendance/',views.trainee_attendance, name='trainee_attendance'),
    path('trainee_attendance_date/',views.trainee_attendance_date, name='trainee_attendance_date'),
    path('trainee_attendance_edit/<str:update_date>',views.trainee_attendance_edit, name='trainee_attendance_edit'),
    path('trainee_attendance_manage/',views.trainee_attendance_manage, name='trainee_attendance_manage'),
    
    path('trainees_profile/<int:id>',views.trainees_profile,name="trainees_profile"),
    path('edit_trainees/<int:id>',views.edit_trainees,name='edit_trainees'),
    path('manage_trainees/<int:id>',views.manage_trainees,name='manage_trainees'),
    path('remove_trainees/',views.remove_trainees,name='remove_trainees'),

    path('register_trainer',views.register_trainer,name='register_trainer'),
    path('view_trainer',views.view_trainer,name='view_trainer'),
    path('trainer_attendance/',views.trainer_attendance, name='trainer_attendance'),
    path('trainer_attendance_date/',views.trainer_attendance_date, name='trainer_attendance_date'),
    path('trainer_attendance_edit/<str:update_date>',views.trainer_attendance_edit, name='trainer_attendance_edit'),
    path('trainer_attendance_manage/',views.trainer_attendance_manage, name='trainer_attendance_manage'),
    path('trainer_profile/<int:id>',views.trainer_profile,name="trainer_profile"),
    path('edit_trainer/<int:id>',views.edit_trainer,name='edit_trainer'),
    path('manage_trainer/<int:id>',views.manage_trainer,name='manage_trainer'),
    path('remove_trainer',views.remove_trainer,name='remove_trainer'),

    path('register_employees/',views.register_employees, name='register_employees'),
    path('view_employees/',views.view_employees, name='view_employees'),
    path('emp_attendance/',views.emp_attendance, name='emp_attendance'),
    path('emp_attendance_date/',views.emp_attendance_date, name='emp_attendance_date'),
    path('emp_profile/<int:id>',views.emp_profile,name="emp_profile"),
    path('emp_attendance_edit/<str:update_date>',views.emp_attendance_edit, name='emp_attendance_edit'),
    path('emp_attendance_manage/',views.emp_attendance_manage, name='emp_attendance_manage'),
    path('edit_employees/<int:id>',views.edit_employees,name='edit_employees'),
    path('manage_employees/<int:id>',views.manage_employees,name='manage_employees'),
    path('remove_employees/',views.remove_employees,name='remove_employees'),

    path('add_salary/',views.add_salary, name='add_salary'),
    path('salary_detail/<int:id>',views.salary_detail, name='salary_detail'),
    path('view_salary/',views.view_salary, name='view_salary'),


    path('register_staff/',views.register_staff, name='register_staff'),
    path('view_staff/',views.view_staff, name='view_staff'),
    path('search/',views.search, name='search'),
    path('staff_attendance/',views.staff_attendance, name='staff_attendance'),
    path('staff_attendance_date/',views.staff_attendance_date, name='staff_attendance_date'),
    path('staff_attendance_edit/<str:update_date>',views.staff_attendance_edit, name='staff_attendance_edit'),
    path('staff_attendance_manage/',views.staff_attendance_manage, name='staff_attendance_manage'),
    path('delete_staff/<int:id>',views.delete_staff,name='delete_staff'),
    path('edit_staff/<int:id>',views.edit_staff,name="edit_staff"),
    path('manage_staff/<int:id>', views.manage_staff,name="manage_staff"),



    path('register_lead/',views.register_lead, name='register_lead'),
    path('view_lead/',views.view_lead, name='view_lead'),
    path('remove_lead/',views.remove_lead,name='remove_lead'),
    path('edit_lead/<int:id>',views.edit_lead,name="edit_lead"),
    path('manage_lead/<int:id>', views.manage_lead,name="manage_lead"),
]

dsgroup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('dashboard/',include('dashboard.urls')),        
    #path('account/',include('account.urls')),   

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from datetime import date 

gender=(
    ('Male','Male'),
    ('Female','Female'),
)
reference=(
    ('facebook','facebook'),
    ('instagram','instagram'),
    ('linkain','linkain'),
    ('twitter','twitter'),
    ('other','other'),
    ('people','people'),
)
state=(
('Andhra Pradesh','Andhra Pradesh'),
('Arunachal Pradesh','Arunachal Pradesh'),
('Asom (Assam)','Asom (Assam)'),
('Bihar','Bihar'),
('Karnataka','Karnataka'),
('Kerala','Kerala'),
('Chhattisgarh','Chhattisgarh'),
('Uttar Pradesh','Uttar Pradesh'),
('Goa','Goa'),
('Gujarat','Gujarat'),
('Haryana','Haryana'),
('Himachal Pradesh','Himachal Pradesh'),
('Jammu and Kashmir','Jammu and Kashmir'),
('Jharkhand','Jharkhand'),
('West Bengal','West Bengal'),
('Madhya Pradesh','Madhya Pradesh'),
('Maharashtra','Maharashtra'),
('Manipur','Manipur'),
('Meghalaya','Meghalaya'),
('Mizoram','Mizoram'),
('Nagaland','Nagaland'),
('Orissa','Orissa'),
('Punjab','Punjab'),
('Rajasthan','Rajasthan'),
('Sikkim','Sikkim'),
('Tamil Nadu','Tamil Nadu'),
('Telangana','Telangana'),
('Tripura','Tripura'),
('Uttarakhand (Uttaranchal)','Uttarakhand (Uttaranchal)'),
)
blood_group=(

    ('A+','A+'),
    ('A-','A-'),
    ('B+','B+'),
    ('B-','B-'),
    ('O+','O+'),
    ('O-','O-'),
    ('AB+','AB+'),
    ('AB-','AB-'),
)
position=(

    ('Beginner','Beginner'),
    ('Intermediate','Intermediate'),
    ('Expert','Expert'),
)


# Create your models here.
class Intern(models.Model):  
    profile = models.FileField(upload_to='media/',blank=True,null=True)  
    intern_name = models.CharField(max_length=100)  
    email = models.EmailField(max_length=100) 
    phone_no = models.CharField(max_length=20,blank=True,null=True)
    aadhar_no = models.CharField(max_length=100,blank=True,null=True)    
    pan_card = models.CharField(max_length=10,blank=True,null=True)   
    gender = models.CharField(max_length=100, choices=gender,null=True)  
    date_of_birth = models.DateField(blank= True,null=True)
    blood_group =  models.CharField(max_length=100, choices=blood_group,null=True)   
    father_name = models.CharField(max_length=100)  
    father_occupation = models.CharField(max_length=100,blank=True,null=True)  
    father_no = models.CharField(max_length=10,blank=True,null=True)     
    city = models.CharField(max_length=100)  
    state = models.CharField(max_length=100, choices=state,null=True)  
    pin_code = models.CharField(max_length=6,blank=True,null=True)     
    address = models.CharField(max_length=100)  
    join_date = models.CharField(max_length=100)
    school_name = models.CharField(max_length=100,blank=True,null=True)
    board = models.CharField(max_length=100,blank=True,null=True)
    passing_year = models.CharField(max_length=4,blank=True,null=True,default=True)

    document_zip = models.FileField(upload_to='media/',blank=True,null=True) 

    high_school_name = models.CharField(max_length=100,blank=True,null=True)
    high_school_board = models.CharField(max_length=100,blank=True,null=True)
    high_school_passing_year = models.CharField(max_length=4,blank=True,null=True,default=True)
    
    intern_cource = models.CharField(max_length=100,blank=True,null=True,default=True)
    startdate = models.CharField(max_length=100,default=True)
    enddate = models.CharField(max_length=100,default=True)

    graduation_univercity = models.CharField(max_length=100,blank=True,null=True)
    graduation_degree = models.CharField(max_length=100,blank=True,null=True)
    graduation_year = models.CharField(max_length=4,blank=True,null=True,default=True)

    
    post_graduation_univercity = models.CharField(max_length=100,blank=True,null=True,default=True)
    post_graduation_degree = models.CharField(max_length=100,blank=True,null=True,default=True)
    post_graduation_year = models.CharField(max_length=4,blank=True,null=True,default=True)

    other_univercity = models.CharField(max_length=100,blank=True,null=True)
    other_degree = models.CharField(max_length=100,blank=True,null=True)
    other_year =models.CharField(max_length=4,blank=True,null=True,default=True)
        
    def __str__(self): 
         return self.intern_name

class InternAttendance(models.Model):
    intern_name= models.ForeignKey('Intern',on_delete=models.CASCADE,default=True)
    attendance = models.CharField(max_length=100)
    half_day = models.CharField(max_length=100,default="No")
    date=models.CharField(max_length=100,default=date.today().strftime("%d-%m-%Y"), blank=True) 

    def __str__(self): 
        return str(self.intern_name)




class Trainer(models.Model):  
    profile = models.FileField(upload_to='media/',blank=True,null=True)  
    trainer_name = models.CharField(max_length=100)  
    email = models.EmailField(max_length=100) 
    phone_no = models.CharField(max_length=20,blank=True,null=True)

    aadhar_no = models.CharField(max_length=12,blank=True,null=True)   
    pan_card = models.CharField(max_length=10,blank=True,null=True)   
    gender = models.CharField(max_length=100, choices=gender,null=True)  
    date_of_birth = models.DateField(blank= True,null=True)
    blood_group = models.CharField(max_length=100,blank=True,null=True)  
    father_name = models.CharField(max_length=100)  
    father_occupation = models.CharField(max_length=100,blank=True,null=True)  
    father_no = models.CharField(max_length=10,blank=True,null=True)   
    city = models.CharField(max_length=100)  
    state = models.CharField(max_length=100)  
    pin_code = models.CharField(max_length=6,blank=True,null=True)    
    address = models.CharField(max_length=100)  
    join_date = models.CharField(max_length=100)

    document_zip = models.FileField(upload_to='media/',blank=True,null=True) 


    school_name = models.CharField(max_length=100,blank=True,null=True)
    board = models.CharField(max_length=100,blank=True,null=True)
    passing_year = models.CharField(max_length=4,blank=True,null=True,default=True)
    
    high_school_name = models.CharField(max_length=100,blank=True,null=True)
    high_school_board = models.CharField(max_length=100,blank=True,null=True)
    high_school_passing_year =models.CharField(max_length=4,blank=True,null=True,default=True)
    

    graduation_univercity = models.CharField(max_length=100,blank=True,null=True)
    graduation_degree = models.CharField(max_length=100,blank=True,null=True)
    graduation_year =models.CharField(max_length=4,blank=True,null=True,default=True)

    post_graduation_univercity = models.CharField(max_length=100,blank=True,null=True)
    post_graduation_degree = models.CharField(max_length=100,blank=True,null=True)
    post_graduation_year =models.CharField(max_length=4,blank=True,null=True,default=True)
    
    
    other_univercity = models.CharField(max_length=100,blank=True,null=True)
    other_degree = models.CharField(max_length=100,blank=True,null=True)
    other_year =models.CharField(max_length=4,blank=True,null=True,default=True)
    

    skill = models.CharField(max_length=100,blank=True,null=True)
    position = models.CharField(max_length=100, choices=position,null=True)
    experience = models.CharField(max_length=100,blank=True,null=True)

    company_name = models.CharField(max_length=100,blank=True,null=True)
    designation = models.CharField(max_length=100,blank=True,null=True)
    contact_no = models.CharField(max_length=10,blank=True,null=True)    
    emails = models.EmailField(max_length=100,blank=True,null=True) 
    refference = models.CharField(max_length=100,blank=True,null=True)
    relationships = models.CharField(max_length=100,blank=True,null=True)
    belongs_department= models.CharField(max_length=100,blank=True,null=True)
    joining_date = models.CharField(max_length=100) 
    living_date =  models.CharField(max_length=100) 

    def __str__(self): 
        return str(self.trainer_name)


class TrainerAttendance(models.Model):
    trainer_name= models.ForeignKey('Trainer',on_delete=models.CASCADE,default=True)
    attendance = models.CharField(max_length=100, default='absent')
    half_day = models.CharField(max_length=100,default="No")
    date=models.CharField(max_length=100,default=date.today().strftime("%d-%m-%Y"), blank=True) 

    def __str__(self): 
        return str(self.trainer_name)



class Trainee(models.Model):
    profile = models.FileField(upload_to='media/',blank=True,null=True)  
    trainee_name = models.CharField(max_length=100)  
    email = models.EmailField(max_length=100) 
    phone_no = models.CharField(max_length=20,blank=True,null=True)
    aadhar_no = models.CharField(max_length=100,blank=True,null=True)    
    pan_card = models.CharField(max_length=10,blank=True,null=True)   
    gender = models.CharField(max_length=100, choices=gender,null=True)  
    date_of_birth = models.DateField(blank= True,null=True)
    blood_group = models.CharField(max_length=100,blank=True,null=True)  
    father_name = models.CharField(max_length=100)  
    father_occupation = models.CharField(max_length=100,blank=True,null=True)  
    father_no = models.CharField(max_length=10,blank=True,null=True)     
    city = models.CharField(max_length=100)  
    state = models.CharField(max_length=100)  
    pin_code = models.CharField(max_length=6,blank=True,null=True)    
    address = models.CharField(max_length=100)  
    join_date = models.CharField(max_length=100)

    document_zip = models.FileField(upload_to='media/',blank=True,null=True) 


    school_name = models.CharField(max_length=100,blank=True,null=True)
    board = models.CharField(max_length=100,blank=True,null=True)
    passing_year = models.CharField(max_length=4,blank=True,null=True,default=True)

    high_school_name = models.CharField(max_length=100,blank=True,null=True)
    high_school_board = models.CharField(max_length=100,blank=True,null=True)
    high_school_passing_year =models.CharField(max_length=4,blank=True,null=True,default=True)

dashboard/templates/dashboard/add_salary.html
{% extends 'dashboard/base.html' %}
{% block maincontain %}

<style>
  label {
    font-weight: 600;
    color: #555;
  }

  .container {}

  .form-control {
    background-color: #ccc;
  }

  .form-select {
    margin-left: 20px;
  }
</style>
<div class="main">

  <section class="signup">
    <div class="container">
      <form method="POST" action="">
        {% csrf_token %}

        <h2 class="text-center">Salary Details</h2>

        <div class="row jumbotron" style="background-color:white;">

          <div class="col-sm-6 form-group" style="margin-top: -20px; text-align:center;">

            <select class="form-control" name=empname>
              {% for object in employee %}
              <option value="{{object.emp_name}}">{{object.emp_name}}</option>
              {% endfor %}
            </select>

            <label for="name">Earnings:</label>

          </div>
          <div class="col-sm-6 form-group" style="margin-top: -20px;text-align:center;">

            <label for="email">Deductions:</label>

          </div>

          <div class="col-sm-6 form-group">
            <label for="Date">Package:</label>
            <input type="text" name="salary" id="salary" class="form-control" placeholder="Employee salary" style="font-size:15px; width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="e_group">TDS</label>
            <input type="int" class="form-control" name="tds" id="TDS" placeholder="TDS" style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="cost_center">Basic</label>
            <input type="text" class="form-control" name="basic" id="Basic" placeholder="Basic" style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="bname">PF</label>
            <input type="text" class="form-control" name="pf" id="PF" placeholder="Provident Fund " style="font-size:15px;width:80%;">

          </div>
          <div class="col-sm-6 form-group">
            <label for="Dname">DA </label>
            <input type="text" class="form-control" name="da" id="DA" placeholder="Dearness Allowance" style="font-size:15px;width:80%;">
          </div>

          <div class="col-sm-6 form-group">
            <label for="cc description">Prof.Tax</label>
            <input type="text" class="form-control" name="prof_tax" id="Prof. Tax" placeholder="Prof. Tax" style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="pan_no">HRA</label>
            <input type="text" class="form-control" name="hra" id="HRA" placeholder="House rent Allowance " style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="created_on">Total Deductions</label>
            <input type="int" class="form-control" name="deductions" id="Total Deductions" placeholder="Total Deductions" style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="created_on">TA</label>
            <input type="int" class="form-control" name="ta" id="TA" placeholder="TA" style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="renew_date">Medical Allowance</label>
            <input type="text" name="medical_allowance" class="form-control datetimepicker" id="Medical Allowance" placeholder="Medical Allowance" style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="created_on">Other</label>
            <input type="int" class="form-control" name="other" id="Other" placeholder="other" style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="renew_date">Net Salary</label>
            <input type="text" name="net_salary" class="form-control datetimepicker" id="Net Salary" placeholder="Net Salary " style="font-size:15px;width:80%;">
          </div>
          <div class="col-sm-6 form-group">
            <label for="renew_date"> Total Earnings</label>
            <input type="text" name="sub_total" class="form-control datetimepicker" id="Sub Total" placeholder="Total" style="font-size:15px;width:80%;">
          </div>

          <div class="col-sm-12 form-group mb-0">
            <button class="btn btn-primary float-right" name="btn" value="submit">
              <h2 style="font-size:20px; font-weight:bold; color:#ffffff;">submit</h2>
            </button>
          </div>

        </div>
      </form>
    </div>

    <script>
      document.getElementById("salary").onchange = function() {
        NetSalary()
      };

      function NetSalary() {
        var Package = parseFloat(document.getElementById("salary").value);
        var monthly = Package / 12;
        var Basic = Math.ceil((Package / 2) / 12);
        var DA = Math.ceil((Package * 0.25) / 12);
        var HRA = Math.ceil((Package * 0.15) / 12);
        var TA = Math.ceil((Package * 0.075) / 12);
        var OTHER = Math.ceil((Package * 0.005) / 12);
        var PF = Math.ceil(((Package + DA) * 0.12) / 12);
        var MA = Math.ceil((Package * 2 / 100) / 12);
        var ProfTax = 200;
        document.getElementById("Basic").value = Basic;
        document.getElementById("DA").value = DA;
        document.getElementById("HRA").value = HRA;
        document.getElementById("TA").value = TA;
        document.getElementById("PF").value = PF;
        document.getElementById("Medical Allowance").value = MA;
        document.getElementById("Other").value = OTHER;
        document.getElementById("Prof. Tax").value = ProfTax;
        var subtotal = document.getElementById("Sub Total").value = Basic + DA + HRA + MA + TA + OTHER;
        if (Package <= 250000) {
          var TDS = document.getElementById("TDS").value = 0;
        } else if (Package > 250000 && Package <= 500000) {
          var TDS = document.getElementById("TDS").value = Basic * 5 / 100;
        } else if (Package > 500000 && Package <= 1000000) {
          var TDS = document.getElementById("TDS").value = 12500 + (Basic * 20 / 100);
        } else {
          var TDS = document.getElementById("TDS").value = 112500 + (Basic * 30 / 100);
        }
        var deduction = document.getElementById("Total Deductions").value = TDS + PF + ProfTax;
        var net_salary = subtotal - deduction;
        document.getElementById('Net Salary').value = Math.ceil(net_salary);
      }
    </script>

    {% endblock maincontain %}

dashboard/templates/dashboard/intern_attendance_date.html
{% extends 'dashboard/base.html' %}
{% block maincontain %}
<div class="container">

  <div class="card">
    <div class="card-header">
      <h2>
        <a class="btn btn-success" href="{% url 'register_intern' %}">Add Intern</a>
        <a class="btn btn-info float-right" href="{% url 'intern_attendance' %}">Take Addendance</a>
      </h2>
    </div>

    <div class="card-body">
      <form action="#" method="post">
        <table class="table table-striped">
          <tr>
            <th width="30%">S/L</th>
            <th width="50%">Attendance Date</th>
            <th width="20%">Action</th>
          </tr>
          {% for d in data %}

          <tr>
            <td style="text-align:left">{{forloop.counter}}</td>
            <td style="text-align:left">{{d.date}}</td>
            <td style="text-align:left">
              <a class="btn btn-primary" href='/dashboard/intern_attendance_edit/{{d.date}}'>View</a>
            </td>
          </tr>
          {% endfor %}
        </table>
      </form>
    </div>
  </div>
</div>

{% endblock maincontain %}

dashboard/templates/dashboard/view_intern.html
{% extends 'dashboard/base.html' %}
{% block maincontain %}
<form action="{% url 'view_interns' %}" method="POST">
  {% csrf_token %}
  <center>
    <div class="input-group">
      <div class="form-outline" style="margin-left: 35%;margin-bottom: none;">
        <input type="search" placeholder="search..." id="form1" name="search" class="form-control" />

      </div>
      <button type="submit" class="btn btn-primary" name='search_btn'>
        <i class="fa fa-search" aria-hidden="true"></i>
      </button>
    </div>
  </center>
  </br></br>
</form>
{{posts}}
{{search_term.intern_name.intern_name}}

<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
  <div class="mdc-card p-0">

    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th  style="text-align:center;margin-left:3px;">Name</th>
            <th style="text-align:center;">Email</th>
            <th style="text-align:center;">Phone Number</th>
            <th style="text-align:center;">Joining Date</th>
            <th style="text-align:center;">Intern Profile</th>
            {% if perms.dashboard.add_intern %}
            <th style="text-align:center;">Action</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for intern in view_intern %}
          <tr>
            <td style="text-align:center;margin-left:3px;">{{intern.intern_name|capfirst}}</td>
            <td style="text-align:center;">{{intern.email}}</td>
            <td style="text-align:center;">{{intern.phone_no}}</td>
            <td style="text-align:center;">{{intern.join_date}}</td>
            <td style="text-align:center;"><a class="btn btn-secondary" href="{% url 'intern_profile' intern.id %}"><i class="fa fa-eye" style="font-size:23px"></i></a></td>
              {% if perms.dashboard.change_intern %}
            <td style="text-align:center;">
              <button class="btn btn-primary" style="background-color:blue;width:40px;"><a href="{% url 'edit_intern' intern.id %}"><i class="fa fa-pencil-square-o" style="font-size:23px;text-align:center;color:white;"></i></a></button>
              {%endif%}
                {% if perms.dashboard.delete_intern %}
              <button type="button" class="btn btn-danger" onclick="get_id({{intern.id}})" data-toggle="modal" data-target="#example" style="width:40px;">
                <i class="fa fa-trash" aria-hidden="true" style="font-size:23px;"></i> </button>
                {%endif%}
              <!-- Modal -->
              <div class="modal fade" id="example" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="examplemodel" style="font-weight:bold;color:black;margin-left:38%;font-size:20px;">Delete Details</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                     {% if perms.dashboard.add_intern %}
                    <div class="modal-body">
                      <h5 style="font-weight:bold;color:#000;margin-left:21%;font-size:15px;"> Are you sure you want to Delete this</h5>
                      <form action="{% url 'remove_intern' %}" method='POST'>
                        {% csrf_token %}
                        <input type='hidden' name='inter_id' id='inter_id'>
                    </div>
                    {%endif%}
                   
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                    </form>
                  </div>
                </div>
              </div>

            </td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  $('#myModal').on('shown.bs.modal', function() {
    $('#myInput').trigger('focus')
  })

  function get_id(id) {
    document.getElementById('inter_id').value = id;
  }
</script>
{% endblock maincontain %}